# Generated by Django 5.2.3 on 2025-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteomics",
            name="log2vals",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="proteomics",
            name="significance",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
