# Generated by Django 5.2.3 on 2025-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinrepeats',
            name='motif_enrichment',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proteinrepeats',
            name='motif_q_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='BleachMeasurement',
        ),
    ]
