# Generated by Django 5.2.3 on 2025-07-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteintf',
            name='parent_organism',
            field=models.ForeignKey(blank=True, help_text='Parent organism of the gene', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proteinTF', to='proteins.organism', verbose_name='Parent organism'),
        ),
    ]
