# Generated by Django 5.2.3 on 2025-09-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='parent_repeat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proteins.repeat', verbose_name='parental repeat'),
        ),
    ]
