# Generated by Django 5.2.3 on 2025-08-05 04:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteomics",
            name="thresholds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
