# Generated by Django 5.2.3 on 2025-09-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_repeat_parent_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeat',
            name='parent_repeat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='proteins.repeat', verbose_name='parental repeat'),
        ),
    ]
