# Generated by Django 5.2.3 on 2025-08-05 05:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0002_proteomics_thresholds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proteomics",
            name="thresholds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(
                    blank=True, decimal_places=2, max_digits=5, null=True
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
