# Generated by Django 5.2.3 on 2025-10-12 05:08

import django.db.models.deletion
import proteins.util.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0003_alter_repeat_parent_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microscopy',
            fields=[
                ('id', models.CharField(default=proteins.util.helpers.shortuuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('local_tiff_file', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('cell_type', models.TextField()),
                ('pixel_size', models.TextField()),
                ('magnification', models.TextField()),
                ('channels', models.JSONField(default=dict)),
                ('expression', models.TextField()),
                ('microscopy', models.TextField()),
                ('description', models.TextField()),
                ('display_name', models.TextField()),
                ('proteintf', models.ForeignKey(db_column='gene', on_delete=django.db.models.deletion.CASCADE, to='proteins.proteintf', to_field='gene', verbose_name='ProteinTF')),
            ],
        ),
    ]
