# Generated by Django 5.2.3 on 2026-01-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0004_microscopy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteomics',
            old_name='target',
            new_name='target_repeat',
        ),
        migrations.AddField(
            model_name='proteomics',
            name='target_protein',
            field=models.ForeignKey(blank=True, help_text='Protein target for this experiment', null=True, on_delete=django.db.models.deletion.CASCADE, to='proteins.proteintf'),
        ),
    ]
