# Generated by Django 5.2.3 on 2026-02-11 05:10

import django.contrib.postgres.fields
import django.db.models.deletion
import proteins.util.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0005_rename_target_proteomics_target_repeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeReferences',
            fields=[
                ('id', models.CharField(default=proteins.util.helpers.shortuuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('reference', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
                ('source', models.TextField(blank=True, max_length=200, null=True)),
                ('organism', models.ForeignKey(blank=True, help_text='Organism from which the gene family was derived', null=True, on_delete=django.db.models.deletion.CASCADE, to='proteins.organism', verbose_name='Reference Organism')),
            ],
        ),
    ]
