# Generated by Django 5.2.3 on 2026-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0006_genomereferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='universal_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
