# Generated by Django 5.2.3 on 2025-09-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favit', '0003_alter_favorite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
